name: GitHub-Profile-Summary-Cards

on:
  schedule: # Se ejecuta cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch: # Te deja ejecutarlo manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
